package crazyeights;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zoeth
 */
public class instructions extends javax.swing.JFrame {

    /**
     * Creates new form instructions
     */
    public instructions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mainMenuBtn = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionText = new javax.swing.JTextArea();
        mainMenuBtn1 = new javax.swing.JButton();

        title1.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 0));
        title1.setText("LEADER BOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mainMenuBtn.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainMenuBtn.setText("MAIN MENU");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 102, 51));

        title2.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 0));
        title2.setText("INSTRUCTIONS");

        instructionText.setEditable(false);
        instructionText.setBackground(new java.awt.Color(0, 102, 51));
        instructionText.setColumns(20);
        instructionText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionText.setForeground(new java.awt.Color(255, 255, 0));
        instructionText.setRows(5);
        instructionText.setText("AIM OF THE GAME:\nThe aim of this game is to be the first player to run out of cards. To score highly, this needs\nto be achieved in as few moves as possible.\n\nBEGINNING THE GAME:\n- Click the play game button from the main menu.\n- Once the new window opens, enter your username, select an amount of players and press OK.\n\nGENERAL GAMEPLAY RULES:\n- Play will begin with you. \n- To play a card from your hand you click it.\n- To pass play between the players, press the next button when prompted by the text displayed\n  in the centre of the window.\n- You can see how many cards each player has left from the indicators located to the left of \n  the suit panel.\n\nYOU ARE ALLOWED TO PLAY CARDS THAT:\n- Match the card on top of the pile in suit\n- Match the card on top of the pile in value\n- Have a value of 8 (doesn't have to match in suit or value)\n\nWILDCARDS:\n- If you play a card with a value of 8, you will be able to choose a suit from the panel in the\n  top right of the window for gameplay to continue in.\n- If the computer plays an 8, you will be alerted via the central text field and the chosen\n  suit will light up in the top right panel until a card of that suit is played.\n- If a 2 is played, the following player will miss a turn and have 2 cards added to their hand.\n- If a 2 is played an affects you, you will be alerted via the central text field and will be\n  promted to press next to pass play to the next player.\n\nEND OF GAME:\n- When a player runs out of cards, gameplay will stop and the main menu button in the bottom \nright hand corner will become enabled, allowing you to return to the main menu.\n- When at the main menu, the leaderboard button can then be clicked to see if your score made \nthe top 5.\n");
        instructionText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        instructionText.setCaretPosition(0);
        jScrollPane1.setViewportView(instructionText);

        mainMenuBtn1.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuBtn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainMenuBtn1.setForeground(new java.awt.Color(0, 102, 51));
        mainMenuBtn1.setText("MAIN MENU");
        mainMenuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(title2))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(mainMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(mainMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        new mainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void mainMenuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtn1ActionPerformed
        new mainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextArea instructionText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton mainMenuBtn1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
