package crazyeights;


import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zoeth
 */
public class leaderBoard extends javax.swing.JFrame {
    ArrayList <String> scores = new ArrayList <String>();
    ArrayList <Integer> values = new ArrayList <Integer>();
    ArrayList <String> topScores = new ArrayList <String>();
    
    boolean clicked = false;
    
    /**
     * Creates new form leaderBoard
     */
    public leaderBoard() {
        initComponents();
    }
    
   
    
    private void readScores(){
        
        clicked = true;
        String fileName = "scores.txt";
        String line = null;
        
        try{
            FileReader fileReader = new FileReader(fileName);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
            while((line = bufferedReader.readLine()) != null){
                scores.add(line);   
            }
            
            bufferedReader.close();
        }
        
        catch(Exception e){
            
        }
        
        
        
        for (int i=0;i<scores.size();i++){
            if (scores.get(i).length()>0){
                int commapos = (scores.get(i)).indexOf(",");
                String strvalue = (scores.get(i)).substring(0,commapos);
                int value = Integer.parseInt(strvalue);
                values.add(value);
            }
        }
        
        Collections.sort(values);
        
        
        while (values.size()> 5){
            values.remove(values.size() - 1);
        }
        
        
        for (int i=0;i<values.size();i++){
            int intvalue = values.get(i);
            for (int j=0;j<scores.size();j++){
                if (scores.get(j).length()>0){
                    int commapos = (scores.get(j)).indexOf(",");
                    String strvalue = (scores.get(j)).substring(0,commapos);
                    int value = Integer.parseInt(strvalue);
                    if (intvalue == value && topScores.size()<5){
                        topScores.add(scores.get(j));
                        scores.remove(scores.get(j));
                    }
                }
            }
        } 
        
        System.out.println("TOPSCORES");
        for (int i = 0; i < topScores.size(); i++){
            System.out.println(topScores.get(i));
        }
        
        System.out.println("SCORES");
        for (int i = 0; i < scores.size(); i++){
            System.out.println(scores.get(i));
        }
    }
    
    

    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        posLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        fourthLabel = new javax.swing.JLabel();
        fifthLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        secondName = new javax.swing.JLabel();
        thirdName = new javax.swing.JLabel();
        fourthName = new javax.swing.JLabel();
        fifthName = new javax.swing.JLabel();
        firstScore = new javax.swing.JLabel();
        secondScore = new javax.swing.JLabel();
        thirdScore = new javax.swing.JLabel();
        fourthScore = new javax.swing.JLabel();
        fifthScore = new javax.swing.JLabel();
        showScoreBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 102, 51));

        title.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 0));
        title.setText("LEADER BOARD");

        panel.setBackground(new java.awt.Color(0, 102, 51));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        posLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        posLabel.setForeground(new java.awt.Color(255, 255, 0));
        posLabel.setText("POSITION");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 0));
        nameLabel.setText("USERNAME");

        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 0));
        scoreLabel.setText("SCORES");

        firstLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstLabel.setForeground(new java.awt.Color(255, 255, 0));
        firstLabel.setText("1st");

        secondLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        secondLabel.setForeground(new java.awt.Color(255, 255, 0));
        secondLabel.setText("2nd");

        thirdLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thirdLabel.setForeground(new java.awt.Color(255, 255, 0));
        thirdLabel.setText("3rd");

        fourthLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourthLabel.setForeground(new java.awt.Color(255, 255, 0));
        fourthLabel.setText("4th");

        fifthLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fifthLabel.setForeground(new java.awt.Color(255, 255, 0));
        fifthLabel.setText("5th");

        firstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 0));
        firstName.setText("-------------");

        secondName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        secondName.setForeground(new java.awt.Color(255, 255, 0));
        secondName.setText("-------------");

        thirdName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thirdName.setForeground(new java.awt.Color(255, 255, 0));
        thirdName.setText("-------------");

        fourthName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourthName.setForeground(new java.awt.Color(255, 255, 0));
        fourthName.setText("-------------");

        fifthName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fifthName.setForeground(new java.awt.Color(255, 255, 0));
        fifthName.setText("-------------");

        firstScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstScore.setForeground(new java.awt.Color(255, 255, 0));
        firstScore.setText("---------");

        secondScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        secondScore.setForeground(new java.awt.Color(255, 255, 0));
        secondScore.setText("---------");

        thirdScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thirdScore.setForeground(new java.awt.Color(255, 255, 0));
        thirdScore.setText("---------");

        fourthScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourthScore.setForeground(new java.awt.Color(255, 255, 0));
        fourthScore.setText("---------");

        fifthScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fifthScore.setForeground(new java.awt.Color(255, 255, 0));
        fifthScore.setText("---------");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(posLabel))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fifthLabel)
                            .addComponent(fourthLabel)
                            .addComponent(thirdLabel)
                            .addComponent(secondLabel)
                            .addComponent(firstLabel))))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(secondName)
                    .addComponent(thirdName)
                    .addComponent(fourthName)
                    .addComponent(fifthName)
                    .addComponent(firstName))
                .addGap(83, 83, 83)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fifthScore)
                    .addComponent(scoreLabel)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(secondScore)
                        .addComponent(thirdScore)
                        .addComponent(fourthScore)
                        .addComponent(firstScore)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posLabel)
                    .addComponent(nameLabel)
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabel)
                    .addComponent(firstName)
                    .addComponent(firstScore))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondLabel)
                    .addComponent(secondName)
                    .addComponent(secondScore))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdLabel)
                    .addComponent(thirdName)
                    .addComponent(thirdScore))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourthLabel)
                    .addComponent(fourthName)
                    .addComponent(fourthScore))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fifthLabel)
                    .addComponent(fifthName)
                    .addComponent(fifthScore))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        showScoreBtn.setBackground(new java.awt.Color(255, 255, 0));
        showScoreBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showScoreBtn.setForeground(new java.awt.Color(0, 102, 51));
        showScoreBtn.setText("SHOW SCORES");
        showScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScoreBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainMenuBtn.setText("MAIN MENU");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(363, 363, 363))))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(showScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScoreBtnActionPerformed
        if (clicked == false){
            readScores();
        }
        
        if (topScores.size()>0){
            int commapos = (topScores.get(0)).indexOf(",");
            firstName.setText(topScores.get(0).substring(commapos+1,topScores.get(0).length()));
            firstScore.setText(topScores.get(0).substring(0,commapos));
        }
        
        if (topScores.size()>1){
            int commapos = (topScores.get(1)).indexOf(",");
            secondName.setText(topScores.get(1).substring(commapos+1,topScores.get(1).length()));
            secondScore.setText(topScores.get(1).substring(0,commapos));
        }
        
        if (topScores.size()>2){
            int commapos = (topScores.get(2)).indexOf(",");
            thirdName.setText(topScores.get(2).substring(commapos+1,topScores.get(2).length()));
            thirdScore.setText(topScores.get(2).substring(0,commapos));
        }
        
        if (topScores.size()>3){
            int commapos = (topScores.get(3)).indexOf(",");
            fourthName.setText(topScores.get(3).substring(commapos+1,topScores.get(3).length()));
            fourthScore.setText(topScores.get(3).substring(0,commapos));
        }
        
        if (topScores.size()>4){
            int commapos = (topScores.get(4)).indexOf(",");
            fifthName.setText(topScores.get(4).substring(commapos+1,topScores.get(4).length()));
            fifthScore.setText(topScores.get(4).substring(0,commapos));
        }
    }//GEN-LAST:event_showScoreBtnActionPerformed

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        clicked = false;
        new mainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaderBoard().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel fifthLabel;
    private javax.swing.JLabel fifthName;
    private javax.swing.JLabel fifthScore;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstScore;
    private javax.swing.JLabel fourthLabel;
    private javax.swing.JLabel fourthName;
    private javax.swing.JLabel fourthScore;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel posLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel secondName;
    private javax.swing.JLabel secondScore;
    private javax.swing.JButton showScoreBtn;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JLabel thirdName;
    private javax.swing.JLabel thirdScore;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}


